### PR TITLE
I created the dashboard according to the UI provided

### PR DESCRIPTION
**Pull request by davidmicah123**
###### CHECKLIST

- [ ] I read [contributing docs](https://github.com/gbowne1/TwitchBot/blob/master/CONTRIBUTING.md)
- [ ] https://davidmicah123.github.io/radio-logger/

### CODE REVIEW

**Comment by gbowne1** [comment]
Looks good.

Approving merge.

**Comment by gbowne1** [comment]
at least 2 two more cards could be added to the Dashboard.

**Comment by davidmicah123** [comment]
okay, i will add it

**Comment by gbowne1** [comment]
Thanks @davidmicah123

**Comment by gbowne1** [comment]
@davidmicah123 I have added you to my organization.  

There's several projects in there if you would like to work on any of them just let me know.

**Comment by davidmicah123** [comment]
okay, i'd let you know

**Comment by gbowne1** [comment]
Thanks @davidmicah123 

Which editor / IDE do you use?

Feel free to comment on any of the issues as well.

**Comment by davidmicah123** [comment]
Visual Studio code

**Comment by gbowne1** [comment]
Good deal thanks @davidmicah123 .  Working in our Website project should be just fine

**Pull request merged**
