### PR TITLE
 Add Ej1seven to the contributor list

### PR DESCRIPTION
**Pull request by Ej1seven**
###### CHECKLIST

- [ ] I read [contributing docs](https://github.com/gbowne1/TwitchBot/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gbowne1** [comment]
@Ej1seven  are you requestimg to collaborate on this project?

**Comment by gbowne1** [comment]
I propose a new file for listing contributors.

CONTRIBUTORS.md or ACKNOWLEDGEMENTS.md

Sample [here] https://github.com/gbowne1/taotnpwaft/blob/master/ACKNOWLEGEDMENTS.md from my other repository.

**Comment by Ej1seven** [comment]
Thanks for the add! I look forward to help resolve some of the issues posted.

**Comment by gbowne1** [comment]
@Ej1seven 

I have added some documentation in markdown [.md] and moved the list of contributors into a new file. 
I will be adding more and more TODO, Issues, Bugs..

Check out the Projects:
  https://github.com/gbowne1/radio-logger/projects/
  https://github.com/users/gbowne1/projects

**Pull request merged**
